language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages: libv8-dev
    - os: linux
      addons:
        apt:
          packages: libnode-dev
    - os: osx
      osx_image: xcode10.1
